### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by reindert-vetter** [chekun/golaravelsession#3]
I think this is an interesting repository. I am working on [Confetti framework](http://www.confetti-framework.com/). Maybe I want to use this in the framework. I was wondering if there is active support on this repository.

**Comment by chekun** [comment]
Thanks for you attention.
Currently, it's a dead repo.  I've completely into `go` field。
I am not sure what type of support to be needed, maybe I can support somehow.

**Comment by reindert-vetter** [comment]
@chekun I have not really a question, but the fact that you react quickly gives me all confidence. 👍
